channels = ["anaconda", "conda-forge"]

[deps]
python = ">=3.7,<=3.11"

[pip.deps]
qiskit              = "==1.1.0"
qiskit-optimization = "==0.6.1"
qiskit-ibm-runtime = "==0.23.0"
qiskit-algorithms   = "==0.3.0"
scipy               = "==1.13.0"
numpy               = "==1.26.0"