channels = ["conda-forge"]

[deps]
python = ">=3.11,<3.12"

[pip.deps]
qiskit              = "~=2.3.0"
qiskit-aer          = "~=0.17.0"
qiskit-ibm-runtime  = "~=0.46.0"
qiskit-optimization = "~=0.7.0"
scipy               = "~=1.15.0"
