name = "QiskitOpt"
uuid = "81b20daf-e62b-4502-a0d1-aa084de80e33"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>"]
version = "0.2.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QUBODrivers = "a3f166f7-2cd3-47b6-9e1e-6fbfe0449eb0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
PythonCall = "0.9.14"
QUBODrivers = "0.3"
julia = "1.9"
