name = "QiskitOpt"
uuid = "81b20daf-e62b-4502-a0d1-aa084de80e33"
authors = ["pedromxavier <pedroxavier@psr-inc.com>", "pedroripper <pedroripper@psr-inc.com>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QUBO = "ce8c2e91-a970-4681-856b-16178c24a30c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
PythonCall = "0.9.20"
julia = "1.9"
QUBO = "0.3.0"
